export type ApplicationSummaryPayload = {
  applicationId: string;
  applicationFields: Record<string, unknown>;
  bankAnalysis: Record<string, unknown>;
  financialOcr: Record<string, unknown>;
  websiteScan: Record<string, unknown>;
};

function buildMemo(payload: ApplicationSummaryPayload) {
  return {
    transaction: {
      application_id: payload.applicationId,
      requested_amount: payload.applicationFields.requested_amount ?? null,
      purpose: payload.applicationFields.purpose ?? null
    },
    overview: payload.applicationFields,
    collateral: payload.applicationFields.collateral ?? null,
    financial_summary: {
      bank_analysis: payload.bankAnalysis,
      ocr: payload.financialOcr
    },
    risks: {
      nsf_events: payload.bankAnalysis.nsf_count ?? 0,
      flags: payload.websiteScan.flags ?? []
    },
    rationale: "Generated by Maya V1 credit summary workflow"
  };
}

export async function generateSummary(payload: ApplicationSummaryPayload): Promise<void> {
  const memo = buildMemo(payload);
  const apiBase = process.env.BF_SERVER_API;

  if (!apiBase) {
    throw new Error("BF_SERVER_API missing");
  }

  const response = await fetch(`${apiBase}/api/credit-summary`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.MAYA_SECRET ?? ""}`
    },
    body: JSON.stringify({
      applicationId: payload.applicationId,
      memo
    })
  });

  if (!response.ok) {
    throw new Error(`applicationSummary.ts failed: ${response.status}`);
  }
}

export default generateSummary;
